image_path: src/data2/images.xlsx
metadata_path: src/data2/metadata_edited.xlsx
manifest_path: docs/iiif
dump_path: src/dump
fields: [
    "http://purl.org/dc/terms/identifier",
    "http://purl.org/dc/terms/description",
    # "http://purl.org/dc/terms/rights",
    # "http://iiif.io/api/presentation/2#attributionLabel",
    # "http://purl.org/dc/terms/isPartOf",
    # "http://iiif.io/api/presentation/2#viewingDirection"
]